version: "3.8"
services:
    redis:
        image: redis
        container_name: cache
        expose:
            - 6379

    web:
        build: .
        ports:
            - "5000:5000"
        environment:
            - REDIS_URL=redis://cache
        depends_on:
            - redis
    